<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Module Namespace
    |--------------------------------------------------------------------------
    |
    | Default module namespace.
    |
    */

    'namespace' => 'Zix',

    'paths' => [
        /*
        |--------------------------------------------------------------------------
        | Plugins path
        |--------------------------------------------------------------------------
        |
        | This path used for save the generated module. This path also will added
        | automatically to list of scanned folders.
        |
        */

        'plugins' => base_path('plugins/'),
        /*
        |--------------------------------------------------------------------------
        | Modules assets path
        |--------------------------------------------------------------------------
        |
        | Here you may update the plugins assets path.
        |
        */

        'assets' => public_path('plugins'),
        /*
        |--------------------------------------------------------------------------
        | The migrations path
        |--------------------------------------------------------------------------
        |
        | Where you run 'module:publish-migration' command, where do you publish the
        | the migration files?
        |
        */

        'migration' => base_path('database/migrations'),
        /*
        |--------------------------------------------------------------------------
        | Generator path
        |--------------------------------------------------------------------------
        |
        | Here you may update the plugins generator path.
        |
        */

        'generator' => [
            'migration' => 'Database/Migrations',
            'seeder' => 'Database/Seeders',
            'factories' => 'Database/Factories',
            'model' => 'Models',
            'controller' => 'Http/Controllers',
            'routes' => 'Http/Routes',
            'events' => 'Events',
            'listeners' => 'Listeners',
            'request' => 'Http/Requests',
            'provider' => 'Providers',
            'test' => 'Tests',
            'assets.admin' => 'Assets/admin',
            'assets.admin.components' => 'Assets/admin/components',
            'assets.admin.pages' => 'Assets/admin/pages',

            'assets.default' => 'Assets/default',
            'assets.default.components' => 'Assets/default/components',
            'assets.default.pages' => 'Assets/default/views',
        ],


    ],

    /*
    |--------------------------------------------------------------------------
    | Module Stubs
    |--------------------------------------------------------------------------
    |
    | Default module stubs.
    |
    */

    'stubs' => [
        'enabled' => false,
        'path' => config('plugins') . '/Core/Commands/stubs',
        'files' => [
            'config' => 'config.json',

            'assets/admin/app' => 'Assets/admin/main.js',
            'assets/admin/routes' => 'Assets/admin/routes.js',

            'assets/default/app' => 'Assets/default/main.js',
            'assets/default/routes' => 'Assets/default/routes.js',

        ],
        'replacements' => [
            'LOWER_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE', 'CLASS', 'NAMESPACE'
        ]
    ],


    /*
    |--------------------------------------------------------------------------
    | Composer File Template
    |--------------------------------------------------------------------------
    |
    | Here is the config for composer.json file, generated by this package
    | in every module since version >= 1.2.0.
    |
    */

    'composer' => [
        'vendor' => 'Zix-plugins',
        'author' => [
            'name' => 'badi ifaoui',
            'email' => 'developers@zixdev.com',
        ],
    ],


];
